### PR TITLE
Working rot13 support.

### LINKED ISSUE #24: Support CW1 CTCP
https://github.com/SoniEx2/CTCP-S/issues/13

(Yes, I actually use this on normal IRC. Most ppl I use this around already use rot13, anyway, so it's not a big deal for them to read it. Ofc, they never bother to send the CTCPs.)

### PR DESCRIPTION
**Pull request by SoniEx2**
Closes #24 (the HELP.md formatting is broken, idk how I'm supposed to fix it)

### CODE REVIEW

**Comment by kensanata** [comment]
Can’t reply in depth because I’m sitting in a park but HELP.md is created using the Makefile in the doc directory.

**Comment by SoniEx2** [comment]
I created it but it's not quite right.

**Comment by SoniEx2** [comment]
(Like, the only issue with it is that I can't do hidden text in markdown)

**Comment by SoniEx2** [comment]
uh, it works I guess. I have no idea how it works (#29).

**Comment by SoniEx2** [comment]
this is good to merge, now. I guess bitlbee does some weird stuff with nicks/accounts before handing us the message.

**Comment by kensanata** [comment]
Thanks!

**Pull request merged**
